name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run tests
      run: |
        pip3 install -U poetry
        poetry install --no-root
        poetry run black --check .
